name: firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  cloud_firestore: ^4.15.1
  firebase_auth: ^4.18.1
  provider: ^6.1.1
  lottie: ^3.3.2
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  cloudinary_public: ^0.23.1
  image_picker: ^1.0.8
  collection: ^1.17.0
  fl_chart: ^0.66.0
  pdf: ^3.10.0
  printing: ^5.11.0
  shared_preferences: ^2.5.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/